apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: database
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso"
          serviceAccountRef:
            name: "default"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: database
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: keycloak-db
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak-db
        property: password
