apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 30m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: authelia
      version: "0.11.6"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    pod:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      env:
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
          value: /secrets/db/password
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
          value: /secrets/ldap/password
      extraVolumes:
        - name: db-password
          secret:
            secretName: authelia-db-credentials
        - name: ldap-password
          secret:
            secretName: lldap-bind-credentials
      extraVolumeMounts:
        - name: db-password
          mountPath: /secrets/db
          readOnly: true
        - name: ldap-password
          mountPath: /secrets/ldap
          readOnly: true
    persistence:
      enabled: true
    ingress:
      enabled: false
    configMap:
      authentication_backend:
        ldap:
          enabled: true
          implementation: lldap
          address: 'ldap://lldap.lldap.svc.cluster.local:3890'
          base_dn: 'dc=osnova,dc=antonsakhanovych,dc=com'
          user: 'cn=admin,ou=people,dc=osnova,dc=antonsakhanovych,dc=com'
          password:
            disabled: true
      storage:
        postgres:
          enabled: true
          address: 'tcp://osnova-db-rw.database.svc.cluster.local:5432'
          database: authelia
          username: authelia
          password:
            disabled: true
      webauthn:
        enable_passkey_login: true
      session:
        cookies:
          - subdomain: auth
            domain: osnova.antonsakhanovych.com
      access_control:
        default_policy: deny
        rules:
          - domain:
              - osnova.antonsakhanovych.com
              - '*.osnova.antonsakhanovych.com'
            policy: one_factor
      notifier:
        filesystem:
          enabled: true
