apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-dns-token
    creationPolicy: Owner
  data:
    - secretKey: api_token
      remoteRef:
        key: cloudflare-dns-token
        property: api_token
