apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-db-password-gen
  namespace: keycloak
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  refreshInterval: "0"
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "keycloak"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-db-password-gen
---
apiVersion: external-secrets.io/v1
kind: PushSecret
metadata:
  name: keycloak-db-credentials-push
  namespace: keycloak
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: openbao
      kind: SecretStore
  selector:
    secret:
      name: keycloak-db-credentials
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: keycloak-db
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: keycloak-db
          property: password
